defaults:
  - dataset: ABIDE
  - model: pmil
  - optimizer: adam
  - training: basic_training
  - datasz: 100p
  - preprocess: non_mixup

seed: 1
log_path: result
save_learnable_graph: False
save_attn_weights: True
save_test_attn_weights: True

# wandb
wandb_entity: PMIL
project: PMIL
